import React, { FormEvent, useEffect, useMemo, useRef, useState } from 'react'
import { createRoot } from 'react-dom/client'
import { BookOpen, Check, Download, FileAudio, Home, Library, Menu, Mic, Moon, Plus, Search, Settings, Sun, Trash2, Upload, X } from 'lucide-react'
import { entities as seedEntities, sessions as seedSessions, proposals, type Entity, type Session } from './data'
import './styles.css'

type Page='home'|'sessions'|'library'|'search'|'transfer'|'settings'|'new'|'review'|'entity'
type Database={entities:Entity[];sessions:Session[];imports:{id:string;name:string;text:string}[]}
const seed:Database={entities:seedEntities,sessions:seedSessions,imports:[]}
const labels:Record<string,string>={NPC:'Персонаж',LOCATION:'Локация',ITEM:'Предмет',QUEST:'Задание',PLAYER_CHARACTER:'Персонаж игрока',FACTION:'Фракция',EVENT:'Событие',IMPORTANT_NOTE:'Заметка'}
const load=():Database=>{try{return JSON.parse(localStorage.getItem('chronicles-db')||'null')||seed}catch{return seed}}
const uid=()=>crypto.randomUUID()

function App(){
 const [db,setDb]=useState(load); const [page,setPage]=useState<Page>('home'); const [selectedId,setSelectedId]=useState(''); const [menu,setMenu]=useState(false); const [theme,setTheme]=useState(localStorage.getItem('theme')||'system'); const [toast,setToast]=useState('')
 useEffect(()=>localStorage.setItem('chronicles-db',JSON.stringify(db)),[db]); useEffect(()=>{document.documentElement.dataset.theme=theme;localStorage.setItem('theme',theme)},[theme]); useEffect(()=>{navigator.serviceWorker?.register('/sw.js').catch(()=>{})},[])
 const go=(p:Page)=>{setPage(p);setMenu(false);window.scrollTo(0,0)}; const notify=(s:string)=>{setToast(s);setTimeout(()=>setToast(''),2200)}
 const saveEntity=(entity:Entity)=>{setDb(d=>({...d,entities:d.entities.some(e=>e.id===entity.id)?d.entities.map(e=>e.id===entity.id?entity:e):[entity,...d.entities]}));setSelectedId(entity.id);go('entity');notify('Сущность сохранена')}
 const deleteEntity=(id:string)=>{if(confirm('Удалить сущность и её факты?')){setDb(d=>({...d,entities:d.entities.filter(e=>e.id!==id)}));go('library');notify('Сущность удалена')}}
 const saveSession=(session:Session)=>{setDb(d=>({...d,sessions:[session,...d.sessions.filter(s=>s.id!==session.id)]}));go('sessions');notify('Сессия сохранена')}
 const selected=db.entities.find(e=>e.id===selectedId)
 return <div className="app"><Sidebar page={page} go={go} open={menu} close={()=>setMenu(false)}/>{menu&&<div className="scrim" onClick={()=>setMenu(false)}/>}<main><header><button className="menu" onClick={()=>setMenu(true)} aria-label="Меню"><Menu/></button><div className="mobile-title">Туманы Баровии</div><button className="icon-btn" onClick={()=>setTheme(theme==='dark'?'light':'dark')} aria-label="Сменить тему">{theme==='dark'?<Sun/>:<Moon/>}</button><button className="primary compact" onClick={()=>go('new')}><Plus/>Новая сессия</button></header>
 {page==='home'&&<HomePage db={db} go={go}/>} {page==='sessions'&&<Sessions db={db} go={go} remove={id=>{if(confirm('Удалить сессию?'))setDb(d=>({...d,sessions:d.sessions.filter(s=>s.id!==id)}))}}/>} {page==='library'&&<LibraryPage items={db.entities} open={id=>{setSelectedId(id);go('entity')}} save={saveEntity}/>} {page==='search'&&<SearchPage db={db} open={id=>{setSelectedId(id);go('entity')}}/>} {page==='transfer'&&<Transfer db={db} setDb={setDb} notify={notify}/>} {page==='settings'&&<SettingsPage theme={theme} setTheme={setTheme} notify={notify}/>} {page==='new'&&<NewSession save={saveSession} go={go}/>} {page==='review'&&<Review saveEntity={saveEntity} go={go} notify={notify}/>} {page==='entity'&&selected&&<EntityPage entity={selected} save={saveEntity} remove={deleteEntity} go={go}/>} </main>{toast&&<div className="toast"><Check size={18}/>{toast}</div>}</div>
}
function Sidebar({page,go,open,close}:{page:Page;go:(p:Page)=>void;open:boolean;close:()=>void}){const nav:[Page,React.ElementType,string][]=[['home',Home,'Обзор'],['sessions',BookOpen,'Сессии'],['library',Library,'Энциклопедия'],['search',Search,'Поиск'],['transfer',Upload,'Импорт и экспорт']];return <aside className={open?'sidebar open':'sidebar'}><div className="brand"><div className="brandmark"><Mic/></div><div><b>Хроники</b><small>TTRPG Dictaphone</small></div><button className="mobile-close" onClick={close}><X/></button></div><div className="campaign"><span className="campaign-icon">Т</span><span><b>Туманы Баровии</b><small>Игрок</small></span></div><nav>{nav.map(([p,I,l])=><button key={p} className={page===p?'active':''} onClick={()=>go(p)}><I size={19}/>{l}</button>)}</nav><div className="side-bottom"><button onClick={()=>go('settings')}><Settings size={19}/>Настройки</button></div></aside>}
function Title({small,title,children}:{small:string;title:string;children?:React.ReactNode}){return <div className="title-row"><div><div className="eyebrow">{small}</div><h1>{title}</h1></div>{children}</div>}
function HomePage({db,go}:{db:Database;go:(p:Page)=>void}){const latest=db.sessions[0];return <div className="content"><Title small="Персональный журнал" title="Туманы Баровии"><span className="role">PLAYER</span></Title><section className="hero"><div className="hero-label">✦ Ранее в кампании</div><h2>{latest?.title||'Начните новую историю'}</h2><p>{latest?.summary||'Создайте первую сессию и запишите голосовой пересказ.'}</p><button className="text-btn" onClick={()=>go('sessions')}>Открыть журнал →</button></section><div className="section-head"><h2>Последние сессии</h2><button onClick={()=>go('sessions')}>Все →</button></div><div className="session-grid">{db.sessions.slice(0,2).map(s=><article className="session-card" key={s.id}><div><small>{s.date}</small><h3>{s.title}</h3><p>{s.summary}</p><span className="done"><Check/> Сохранено</span></div></article>)}</div><div className="section-head"><h2>Энциклопедия</h2><button onClick={()=>go('library')}>Открыть →</button></div><div className="stats">{['NPC','LOCATION','ITEM','QUEST'].map(t=><div key={t}><b>{db.entities.filter(e=>e.type===t).length}</b><span>{labels[t]}</span></div>)}</div></div>}
function Sessions({db,go,remove}:{db:Database;go:(p:Page)=>void;remove:(id:string)=>void}){return <div className="content"><Title small="Журнал кампании" title="Сессии"><button className="primary" onClick={()=>go('new')}><Plus/>Добавить</button></Title><div className="list">{db.sessions.map(s=><article className="list-card" key={s.id}><div className="date-large">{s.date}</div><div className="grow"><span className="pill">{s.status==='review'?'ТРЕБУЕТ REVIEW':'ГОТОВО'}</span><h2>{s.title}</h2><p>{s.summary||'Нет заметки'}</p><small><FileAudio/> {s.duration}</small></div><button className="ghost danger" onClick={()=>remove(s.id)}><Trash2 size={17}/></button></article>)}</div></div>}
function EntityForm({initial,onSave,onClose}:{initial?:Entity;onSave:(e:Entity)=>void;onClose:()=>void}){const submit=(ev:FormEvent<HTMLFormElement>)=>{ev.preventDefault();const f=new FormData(ev.currentTarget);onSave({id:initial?.id||uid(),name:String(f.get('name')),type:String(f.get('type')),description:String(f.get('description')),tag:String(f.get('tag')||''),facts:String(f.get('facts')||'').split('\n').map(x=>x.trim()).filter(Boolean)})};return <div className="modal-back"><form className="modal panel form" onSubmit={submit}><button type="button" className="modal-x" onClick={onClose}><X/></button><h2>{initial?'Изменить сущность':'Новая сущность'}</h2><label>Название<input required name="name" defaultValue={initial?.name}/></label><label>Тип<select name="type" defaultValue={initial?.type||'NPC'}>{['PLAYER_CHARACTER','NPC','LOCATION','ITEM','EVENT','QUEST','FACTION','IMPORTANT_NOTE'].map(t=><option key={t} value={t}>{labels[t]||t}</option>)}</select></label><label>Описание<textarea name="description" defaultValue={initial?.description}/></label><label>Метка<input name="tag" defaultValue={initial?.tag}/></label><label>Факты, по одному на строку<textarea name="facts" defaultValue={initial?.facts.join('\n')}/></label><button className="primary" type="submit">Сохранить</button></form></div>}
function LibraryPage({items,open,save}:{items:Entity[];open:(id:string)=>void;save:(e:Entity)=>void}){const [filter,setFilter]=useState('ALL');const [adding,setAdding]=useState(false);return <div className="content"><Title small="База знаний" title="Энциклопедия"><button className="primary" onClick={()=>setAdding(true)}><Plus/>Добавить</button></Title><div className="filters">{['ALL','NPC','LOCATION','ITEM','QUEST'].map(t=><button key={t} className={filter===t?'active':''} onClick={()=>setFilter(t)}>{t==='ALL'?'Все':labels[t]}</button>)}</div><div className="entity-grid">{items.filter(e=>filter==='ALL'||e.type===filter).map(e=><button className="entity-card" key={e.id} onClick={()=>open(e.id)}><span className={'entity-icon '+e.type.toLowerCase()}>{e.name[0]}</span><span><small>{labels[e.type]||e.type}</small><b>{e.name}</b><p>{e.description}</p></span></button>)}</div>{adding&&<EntityForm onClose={()=>setAdding(false)} onSave={e=>{save(e);setAdding(false)}}/>}</div>}
function EntityPage({entity,save,remove,go}:{entity:Entity;save:(e:Entity)=>void;remove:(id:string)=>void;go:(p:Page)=>void}){const [editing,setEditing]=useState(false);return <div className="content narrow"><button className="back" onClick={()=>go('library')}>← Энциклопедия</button><div className="entity-heading"><span className="entity-icon huge">{entity.name[0]}</span><div><div className="eyebrow">{labels[entity.type]||entity.type}</div><h1>{entity.name}</h1></div><button className="ghost" onClick={()=>setEditing(true)}>Изменить</button><button className="ghost danger" onClick={()=>remove(entity.id)}><Trash2/></button></div><section className="panel detail"><h3>Описание</h3><p>{entity.description||'Описание не добавлено.'}</p><hr/><h3>Факты</h3>{entity.facts.length?entity.facts.map(f=><div className="fact" key={f}><span className="fact-check"><Check/></span><b>{f}</b></div>):<p>Фактов пока нет.</p>}</section>{editing&&<EntityForm initial={entity} onClose={()=>setEditing(false)} onSave={e=>{save(e);setEditing(false)}}/>}</div>}
function SearchPage({db,open}:{db:Database;open:(id:string)=>void}){const [q,setQ]=useState('');const found=useMemo(()=>db.entities.filter(e=>(e.name+' '+e.description+' '+e.facts.join(' ')).toLowerCase().includes(q.toLowerCase())),[q,db]);return <div className="content"><Title small="В активной кампании" title="Поиск"/><div className="searchbox"><Search/><input value={q} onChange={e=>setQ(e.target.value)} placeholder="Имена, места, факты…" autoFocus/></div><p className="result-count">{q?`Найдено: ${found.length}`:'Введите запрос'}</p><div className="entity-grid">{q&&found.map(e=><button key={e.id} className="entity-card" onClick={()=>open(e.id)}><b>{e.name}</b><p>{e.description}</p></button>)}</div></div>}
function NewSession({save,go}:{save:(s:Session)=>void;go:(p:Page)=>void}){const [recording,setRecording]=useState(false);const [audio,setAudio]=useState('');const [defaults]=useState(()=>({title:'Новая сессия',date:new Date().toISOString().slice(0,10)}));const recorder=useRef<MediaRecorder|null>(null);const chunks=useRef<Blob[]>([]);const toggle=async()=>{if(recording){recorder.current?.stop();setRecording(false);return}try{const stream=await navigator.mediaDevices.getUserMedia({audio:true});chunks.current=[];const r=new MediaRecorder(stream);r.ondataavailable=e=>chunks.current.push(e.data);r.onstop=()=>{setAudio(URL.createObjectURL(new Blob(chunks.current)));stream.getTracks().forEach(t=>t.stop())};r.start();recorder.current=r;setRecording(true)}catch{alert('Нет доступа к микрофону. Разрешите его в настройках браузера.')}};const submit=(e:FormEvent<HTMLFormElement>)=>{e.preventDefault();const f=new FormData(e.currentTarget);save({id:uid(),title:String(f.get('title')),date:String(f.get('date')),summary:String(f.get('summary')),duration:audio?'Аудио прикреплено':'Без аудио',status:'review'})};return <div className="content narrow"><button className="back" onClick={()=>go('sessions')}>← Назад</button><Title small="Новая запись" title="Расскажите, что произошло"/><form onSubmit={submit}><section className="panel form"><label>Название<input required name="title" defaultValue={defaults.title}/></label><label>Дата<input required type="date" name="date" defaultValue={defaults.date}/></label><label>Заметка / транскрипция<textarea name="summary" placeholder="Текст можно отредактировать перед сохранением"/></label></section><section className={recording?'recorder recording':'recorder'}><div className="rings"><button type="button" onClick={toggle}><Mic/></button></div><h2>{recording?'Идёт запись…':'Записать пересказ'}</h2>{audio&&<audio controls src={audio}/>}<label className="upload-wide"><FileAudio/><span>Загрузить аудио</span><input hidden type="file" accept="audio/*" onChange={e=>e.target.files?.[0]&&setAudio(URL.createObjectURL(e.target.files[0]))}/></label></section><button className="primary submit">Сохранить сессию</button></form></div>}
function download(name:string,text:string,type:string){const a=document.createElement('a');a.href=URL.createObjectURL(new Blob([text],{type}));a.download=name;a.click();URL.revokeObjectURL(a.href)}
function Transfer({db,setDb,notify}:{db:Database;setDb:React.Dispatch<React.SetStateAction<Database>>;notify:(s:string)=>void}){const importFile=async(file:File)=>{if(!/\.(md|txt)$/i.test(file.name)){alert('Поддерживаются только .md и .txt');return}const text=await file.text();setDb(d=>({...d,imports:[...d.imports,{id:uid(),name:file.name,text}]}));notify('Документ сохранён как источник — канонические данные не изменены')};const json=()=>download('campaign.json',JSON.stringify({format:'ttrpg-dictaphone',version:1,exportedAt:new Date().toISOString(),campaign:{name:'Туманы Баровии'},sessions:db.sessions,entities:db.entities,facts:db.entities.flatMap(e=>e.facts.map(value=>({entityId:e.id,value,origin:'MANUAL'}))),relations:[]},null,2),'application/json');const md=()=>download('campaign.md',`# Туманы Баровии\n\n## Сессии\n${db.sessions.map(s=>`### ${s.title}\n${s.date}\n\n${s.summary}`).join('\n\n')}\n\n## Энциклопедия\n${db.entities.map(e=>`### ${e.name}\n${e.description}\n${e.facts.map(f=>`- ${f}`).join('\n')}`).join('\n\n')}`,'text/markdown');return <div className="content"><Title small="Данные принадлежат вам" title="Импорт и экспорт"/><div className="two-cols"><section className="panel"><Upload className="feature-icon"/><h2>Импорт заметок</h2><p>Файл сохраняется как исходный документ и не меняет энциклопедию без Review.</p><label className="primary">Выбрать .md или .txt<input hidden type="file" accept=".md,.txt,text/plain,text/markdown" onChange={e=>e.target.files?.[0]&&importFile(e.target.files[0])}/></label><p>Источников: {db.imports.length}</p></section><section className="panel"><Download className="feature-icon"/><h2>Экспорт кампании</h2><p>Полная переносимая копия пользовательских данных.</p><div className="button-row"><button className="primary" onClick={json}>JSON</button><button className="ghost" onClick={md}>Markdown</button></div></section></div></div>}
function SettingsPage({theme,setTheme,notify}:{theme:string;setTheme:(s:string)=>void;notify:(s:string)=>void}){return <div className="content narrow"><Title small="Локальные настройки" title="Настройки"/><section className="panel settings"><h3>Оформление</h3><div className="theme-options">{['light','dark','system'].map(t=><button key={t} className={theme===t?'active':''} onClick={()=>setTheme(t)}>{t==='light'?'Светлая':t==='dark'?'Тёмная':'Системная'}</button>)}</div><hr/><h3>Хранение аудио</h3><label className="radio"><input type="radio" name="audio" defaultChecked/><span><b>Удалять после подтверждения</b><small>До подтверждения транскрипции запись остаётся доступной</small></span></label><label className="radio"><input type="radio" name="audio"/><span><b>Хранить всегда</b></span></label><hr/><p>AI-операции выполняются только через серверные провайдеры. Платный fallback автоматически не включается.</p><button className="primary" onClick={()=>notify('Настройки сохранены')}>Сохранить</button></section></div>}
function Review({saveEntity,go,notify}:{saveEntity:(e:Entity)=>void;go:(p:Page)=>void;notify:(s:string)=>void}){const [accepted,setAccepted]=useState(proposals.map(()=>true));const commit=()=>{proposals.forEach((p,i)=>{if(accepted[i]&&p.kind.startsWith('NEW ')){const type=p.kind.replace('NEW ','');if(type!=='FACT')saveEntity({id:uid(),name:p.name,type:type==='NPC'?'NPC':type==='QUEST'?'QUEST':'IMPORTANT_NOTE',description:p.detail,facts:[`Источник ${p.block}: ${p.source}`]})}});notify('Принятые предложения применены');go('library')};return <div className="content"><Title small="AI предлагает — вы решаете" title="Review"><span>{accepted.filter(Boolean).length} выбрано</span></Title><div className="review-layout"><div className="proposal-list">{proposals.map((p,i)=><article className={accepted[i]?'proposal accepted':'proposal'} key={p.kind+p.name}><span className="pill">{p.kind}</span><h2>{p.name}</h2><p>{p.detail}</p><div className="source"><small>{p.block} · {p.confidence}</small>“{p.source}”</div><div className="proposal-actions"><button className={accepted[i]?'accept':''} onClick={()=>setAccepted(a=>a.map((v,n)=>n===i?!v:v))}>{accepted[i]?'Принято':'Принять'}</button><button onClick={()=>setAccepted(a=>a.map((v,n)=>n===i?false:v))}>Отклонить</button></div></article>)}</div><aside className="commit-box"><h3>Подтвердить изменения</h3><p>Только выбранные карточки попадут в базу знаний.</p><button className="primary" onClick={commit}>Применить</button></aside></div></div>}
createRoot(document.getElementById('root')!).render(<React.StrictMode><App/></React.StrictMode>)
