import React, { useEffect, useMemo, useState } from 'react'
import { createRoot } from 'react-dom/client'
import { BookOpen, Check, ChevronDown, CircleUserRound, Clock3, Download, FileAudio, FileUp, Home, Library, Menu, Mic, Moon, Plus, Search, Settings, Sparkles, Sun, Upload, X } from 'lucide-react'
import { entities, proposals, sessions } from './data'
import './styles.css'

type Page = 'home'|'sessions'|'library'|'search'|'transfer'|'settings'|'new'|'review'|'entity'
const typeLabels: Record<string,string>={NPC:'Персонаж',LOCATION:'Локация',ITEM:'Предмет',QUEST:'Задание'}

function App(){
 const [page,setPage]=useState<Page>('home'); const [menu,setMenu]=useState(false); const [theme,setTheme]=useState(localStorage.getItem('theme')||'dark');
 const [query,setQuery]=useState(''); const [selected,setSelected]=useState(entities[0]); const [toast,setToast]=useState('');
 useEffect(()=>{document.documentElement.dataset.theme=theme;localStorage.setItem('theme',theme)},[theme])
 useEffect(()=>{if('serviceWorker' in navigator) navigator.serviceWorker.register('/sw.js').catch(()=>{})},[])
 const go=(p:Page)=>{setPage(p);setMenu(false);scrollTo(0,0)}
 const notify=(s:string)=>{setToast(s);setTimeout(()=>setToast(''),2500)}
 const nav=[['home',Home,'Обзор'],['sessions',BookOpen,'Сессии'],['library',Library,'Энциклопедия'],['search',Search,'Поиск'],['transfer',Upload,'Импорт и экспорт'] ] as const
 return <div className="app">
  <aside className={menu?'sidebar open':'sidebar'}>
   <div className="brand"><div className="brandmark"><Mic size={20}/></div><div><b>Хроники</b><small>TTRPG Dictaphone</small></div><button className="mobile-close" onClick={()=>setMenu(false)}><X/></button></div>
   <button className="campaign"><span className="campaign-icon">С</span><span><b>Туманы Баровии</b><small>Игрок · 12 сессий</small></span><ChevronDown size={16}/></button>
   <nav>{nav.map(([id,I,label])=><button key={id} className={page===id?'active':''} onClick={()=>go(id)}><I size={19}/>{label}</button>)}</nav>
   <div className="side-bottom"><button onClick={()=>go('settings')}><Settings size={19}/>Настройки</button><div className="profile"><CircleUserRound/><span><b>Алексей</b><small>alex@example.com</small></span></div></div>
  </aside>
  {menu&&<div className="scrim" onClick={()=>setMenu(false)}/>}<main>
   <header><button className="menu" onClick={()=>setMenu(true)}><Menu/></button><div className="mobile-title">Туманы Баровии</div><button className="icon-btn" aria-label="Тема" onClick={()=>setTheme(theme==='dark'?'light':'dark')}>{theme==='dark'?<Sun/>:<Moon/>}</button><button className="primary compact" onClick={()=>go('new')}><Plus/>Новая сессия</button></header>
   {page==='home'&&<HomePage go={go}/>} {page==='sessions'&&<SessionsPage go={go}/>} {page==='library'&&<LibraryPage open={(e)=>{setSelected(e);go('entity')}}/>}
   {page==='search'&&<SearchPage query={query} setQuery={setQuery} open={(e)=>{setSelected(e);go('entity')}}/>} {page==='transfer'&&<Transfer notify={notify}/>} {page==='settings'&&<SettingsPage theme={theme} setTheme={setTheme} notify={notify}/>} {page==='new'&&<NewSession go={go} notify={notify}/>} {page==='review'&&<Review go={go} notify={notify}/>} {page==='entity'&&<EntityPage entity={selected} go={go}/>}
  </main>{toast&&<div className="toast"><Check size={18}/>{toast}</div>}
 </div>
}

function Title({eyebrow,title,children}:{eyebrow?:string,title:string,children?:React.ReactNode}){return <div className="title-row"><div>{eyebrow&&<div className="eyebrow">{eyebrow}</div>}<h1>{title}</h1></div>{children}</div>}
function HomePage({go}:{go:(p:Page)=>void}){return <div className="content"><Title eyebrow="Добрый вечер, Алексей" title="Туманы Баровии"><span className="role">PLAYER</span></Title><section className="hero"><div className="hero-label"><Sparkles size={16}/> Ранее в кампании</div><h2>Тени сгущаются над Валлаки</h2><p>Вы добрались до города вместе с Ириной и нашли временное убежище в таверне «Синяя вода». Отец Люциан рассказал, что священные кости исчезли — и без них церковь больше не защищена.</p><div className="threads"><span>Найти кости святого Андрала</span><span>Узнать больше о Риктавио</span></div><button className="text-btn">Читать полный recap →</button></section><div className="section-head"><div><span>Последние записи</span><h2>Сессии</h2></div><button onClick={()=>go('sessions')}>Все сессии →</button></div><div className="session-grid">{sessions.slice(0,2).map((s,i)=><article className="session-card" key={s.id}><div className="datebox"><b>{i?2:9}</b><span>АВГ</span></div><div><small>СЕССИЯ {s.id}</small><h3>{s.title}</h3><p>{s.summary}</p><div className="meta"><Clock3/> {s.duration}<span className="done"><Check/> Обработано</span></div></div></article>)}</div><div className="section-head"><div><span>База знаний</span><h2>Энциклопедия</h2></div><button onClick={()=>go('library')}>Открыть →</button></div><div className="stats"><div><b>18</b><span>Персонажей</span></div><div><b>12</b><span>Локаций</span></div><div><b>7</b><span>Заданий</span></div><div><b>24</b><span>События</span></div></div></div>}
function SessionsPage({go}:{go:(p:Page)=>void}){return <div className="content"><Title eyebrow="Журнал кампании" title="Сессии"><button className="primary" onClick={()=>go('new')}><Plus/>Новая сессия</button></Title><div className="list">{sessions.map(s=><article className="list-card" key={s.id}><div className="date-large">{s.date}</div><div className="grow"><span className="pill">СЕССИЯ {s.id}</span><h2>{s.title}</h2><p>{s.summary}</p><small><FileAudio/> {s.duration} · Транскрипция подтверждена</small></div><button className="ghost">Открыть</button></article>)}</div></div>}
function LibraryPage({open}:{open:(e:typeof entities[0])=>void}){const [filter,setFilter]=useState('ALL');return <div className="content"><Title eyebrow="База знаний" title="Энциклопедия"><button className="primary"><Plus/>Добавить</button></Title><div className="filters">{['ALL','NPC','LOCATION','ITEM','QUEST'].map(f=><button key={f} className={filter===f?'active':''} onClick={()=>setFilter(f)}>{f==='ALL'?'Все':typeLabels[f]}</button>)}</div><div className="entity-grid">{entities.filter(e=>filter==='ALL'||e.type===filter).map(e=><button className="entity-card" key={e.id} onClick={()=>open(e)}><span className={'entity-icon '+e.type.toLowerCase()}>{e.name[0]}</span><span className="grow"><small>{typeLabels[e.type]}</small><b>{e.name}</b><p>{e.description}</p></span>{e.tag&&<span className="tag">{e.tag}</span>}</button>)}</div></div>}
function SearchPage({query,setQuery,open}:{query:string,setQuery:(s:string)=>void,open:(e:typeof entities[0])=>void}){const result=useMemo(()=>entities.filter(e=>(e.name+e.description+e.facts.join(' ')).toLowerCase().includes(query.toLowerCase())),[query]);return <div className="content"><Title eyebrow="Только в этой кампании" title="Поиск"/><div className="searchbox"><Search/><input autoFocus value={query} onChange={e=>setQuery(e.target.value)} placeholder="Имена, места, факты, записи…"/></div><p className="result-count">{query?`Найдено: ${result.length}`:'Введите запрос для поиска по всей кампании'}</p>{query&&<div className="entity-grid">{result.map(e=><button key={e.id} className="entity-card" onClick={()=>open(e)}><span className="entity-icon">{e.name[0]}</span><span><small>{typeLabels[e.type]}</small><b>{e.name}</b><p>{e.description}</p></span></button>)}</div>}</div>}
function Transfer({notify}:{notify:(s:string)=>void}){return <div className="content"><Title eyebrow="Ваши данные принадлежат вам" title="Импорт и экспорт"/><div className="two-cols"><section className="panel"><FileUp className="feature-icon"/><h2>Импорт заметок</h2><p>Загрузите Markdown или обычный текст. Импорт создаст черновик для проверки — данные не попадут в энциклопедию автоматически.</p><button className="primary" onClick={()=>notify('Документ выбран для импорта')}><Upload/>Выбрать .md или .txt</button></section><section className="panel"><Download className="feature-icon"/><h2>Экспорт кампании</h2><p>Скачайте все сессии, сущности, факты, связи и источники. Экспорт совместим с будущими версиями.</p><div className="button-row"><button className="primary" onClick={()=>notify('JSON-экспорт подготовлен')}><Download/>JSON</button><button className="ghost" onClick={()=>notify('Markdown-экспорт подготовлен')}>Markdown</button></div></section></div></div>}
function SettingsPage({theme,setTheme,notify}:{theme:string,setTheme:(s:string)=>void,notify:(s:string)=>void}){return <div className="content narrow"><Title eyebrow="Профиль и кампания" title="Настройки"/><section className="panel settings"><h3>Оформление</h3><p>Выберите удобную тему интерфейса.</p><div className="theme-options">{['light','dark','system'].map(t=><button key={t} className={theme===t?'active':''} onClick={()=>setTheme(t)}>{t==='light'?'Светлая':t==='dark'?'Тёмная':'Системная'}</button>)}</div><hr/><h3>Хранение аудио</h3><label className="radio"><input type="radio" defaultChecked name="audio"/><span><b>Удалять после подтверждения</b><small>Аудио удалится только когда вы проверите транскрипцию</small></span></label><label className="radio"><input type="radio" name="audio"/><span><b>Хранить всегда</b><small>Оригинал останется доступен у каждой сессии</small></span></label><hr/><h3>AI-провайдеры</h3><p>Аудио отправляется в Groq Whisper, текст — в Gemini. Платный API никогда не подключается автоматически.</p><button className="primary" onClick={()=>notify('Настройки сохранены')}>Сохранить</button></section></div>}
function NewSession({go,notify}:{go:(p:Page)=>void,notify:(s:string)=>void}){const [recording,setRecording]=useState(false);return <div className="content narrow"><button className="back" onClick={()=>go('sessions')}>← Назад к сессиям</button><Title eyebrow="Новая запись" title="Расскажите, что произошло"/><section className="panel form"><label>Название сессии<input defaultValue="Сессия 13"/></label><div className="form-row"><label>Дата<input type="date" defaultValue="2026-08-11"/></label><label>Режим<select><option>Знания игрока</option><option>Заметки мастера</option></select></label></div><label>Короткая заметка<textarea placeholder="Необязательно: игроки, ключевой момент…"/></label></section><section className={recording?'recorder recording':'recorder'}><div className="rings"><button onClick={()=>setRecording(!recording)}><Mic/></button></div><h2>{recording?'Идёт запись…':'Записать пересказ'}</h2><p>{recording?'00:18 · Нажмите, чтобы остановить':'До 5 минут · можно поставить на паузу'}</p></section><div className="or"><span/>или<span/></div><button className="upload-wide" onClick={()=>notify('Выберите аудиофайл')}><FileAudio/><span><b>Загрузить аудиофайл</b><small>WEBM, MP3, M4A, WAV или OGG</small></span></button><button className="primary submit" onClick={()=>go('review')}>Продолжить с демо-транскрипцией →</button></div>}
function Review({go,notify}:{go:(p:Page)=>void,notify:(s:string)=>void}){const [accepted,setAccepted]=useState<boolean[]>(proposals.map(()=>true));return <div className="content"><button className="back" onClick={()=>go('sessions')}>← Сессия 13</button><Title eyebrow="AI-анализ завершён" title="Проверьте изменения"><span className="review-count">{accepted.filter(Boolean).length} из {proposals.length} выбрано</span></Title><div className="review-summary"><div><b>2</b><span>Новые сущности</span></div><div><b>1</b><span>Новый факт</span></div><div><b>0</b><span>Конфликты</span></div></div><div className="review-layout"><div className="proposal-list">{proposals.map((p,i)=><article key={p.kind+p.name} className={accepted[i]?'proposal accepted':'proposal'}><div className="proposal-top"><span className="pill">{p.kind}</span><span className="confidence">{p.confidence} уверенность</span></div><h2>{p.name}</h2><p>{p.detail}</p><div className="source"><small>ИСТОЧНИК · {p.block}</small>“{p.source}”</div><div className="proposal-actions"><button className={accepted[i]?'accept':''} onClick={()=>setAccepted(a=>a.map((v,n)=>n===i?!v:v))}>{accepted[i]?<><Check/>Принято</>:<>Принять</>}</button><button>Изменить</button><button onClick={()=>setAccepted(a=>a.map((v,n)=>n===i?false:v))}>Отклонить</button></div></article>)}</div><aside className="commit-box"><Sparkles/><h3>Всё готово?</h3><p>Выбранные изменения попадут в энциклопедию одной операцией. Их можно отменить позже.</p><button className="primary" onClick={()=>{notify('Изменения добавлены в энциклопедию');go('home')}}>Применить {accepted.filter(Boolean).length} изменения</button><small>AI ничего не изменит без вашего подтверждения.</small></aside></div></div>}
function EntityPage({entity,go}:{entity:typeof entities[0],go:(p:Page)=>void}){return <div className="content narrow"><button className="back" onClick={()=>go('library')}>← Энциклопедия</button><div className="entity-heading"><span className={'entity-icon huge '+entity.type.toLowerCase()}>{entity.name[0]}</span><div><span className="eyebrow">{typeLabels[entity.type]}</span><h1>{entity.name}</h1>{entity.tag&&<span className="tag">{entity.tag}</span>}</div><button className="ghost">Изменить</button></div><section className="panel detail"><h3>Описание</h3><p>{entity.description}</p><hr/><h3>Факты</h3>{entity.facts.map((f,i)=><div key={f} className="fact"><span className="fact-check"><Check/></span><div><b>{f}</b><small>Подтверждено · Сессия {12-i}</small></div><button>•••</button></div>)}<hr/><h3>Источники</h3><button className="source-link"><BookOpen/>Сессия 12 — Тени над Валлаки <span>Открыть →</span></button></section></div>}

createRoot(document.getElementById('root')!).render(<React.StrictMode><App/></React.StrictMode>)
